import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  goByExampleSidebar: [
    'index',
    'hello-world',
    'values',
    'variables',
    'constants',
    'for',
    'if-else',
    'switch',
    'arrays',
    'slices',
    'maps',
    'functions',
    'multiple-return-values',
    'variadic-functions',
    'closures',
    'recursion',
    'range-over-built-in-types',
    'pointers',
    'strings-and-runes',
    'structs',
    'methods',
    'interfaces',
    'enums',
    'struct-embedding',
    'generics',
    'range-over-iterators',
    'errors',
    'custom-errors',
    'visibility-and-packages',
    'goroutines',
    'goroutine-lifecycle',
    'channels',
    'channel-buffering',
    'channel-synchronization',
    'channel-directions',
    'select',
    'timeouts',
    'non-blocking-channel-operations',
    'closing-channels',
    'range-over-channels',
    'timers',
    'tickers',
    'worker-pools',
    'waitgroups',
    'rate-limiting',
    'atomic-counters',
    'mutexes',
    'stateful-goroutines',
    'sorting',
    'sorting-by-functions',
    'panic',
    'defer',
    'recover',
    'string-functions',
    'string-formatting',
    'text-templates',
    'regular-expressions',
    'json',
    'xml',
    'time',
    'epoch',
    'time-formatting-parsing',
    'random-numbers',
    'number-parsing',
    'url-parsing',
    'sha256-hashes',
    'base64-encoding',
    'reading-files',
    'writing-files',
    'line-filters',
    'file-paths',
    'directories',
    'temporary-files-and-directories',
    'embed-directive',
    'testing-and-benchmarking',
    'unit-testing',
    'command-line-arguments',
    'command-line-flags',
    'command-line-subcommands',
    'environment-variables',
    'logging',
    'http-client',
    'http-server',
    'tcp-server',
    'context',
    'context-cancellation',
    'spawning-processes',
    'execing-processes',
    'signals',
    'exit',
  ],
  goEditorialSidebar: [
    {type: 'doc', id: 'index', label: 'Início'},
    {
      type: 'category',
      label: '2026',
      collapsible: false,
      items: [
        {
          type: 'link',
          label: 'API HTTP em Go',
          href: '/go-http-api',
          description: 'Stdlib, middleware e JSON sem framework.',
          customProps: {date: '13 set 2026'},
        },
        {
          type: 'link',
          label: 'Testes em Go',
          href: '/go-testes',
          description: 'Tabela, -race e o que validar.',
          customProps: {date: '13 set 2026'},
        },
        {
          type: 'link',
          label: 'Worker pool em Go',
          href: '/go-worker-pool',
          description: 'Fila, limite e shutdown limpo.',
          customProps: {date: '13 set 2026'},
        },
        {
          type: 'link',
          label: 'Defer, panic e recover em Go',
          href: '/go-defer-panic',
          description: 'LIFO, argumentos e a regra.',
          customProps: {date: '13 set 2026'},
        },
        {
          type: 'link',
          label: 'sync.Map em Go',
          href: '/go-sync-map',
          description: 'Read/dirty, LoadOrStore e quando usar.',
          customProps: {date: '13 set 2026'},
        },
        {
          type: 'link',
          label: 'CAP e PACELC na prática',
          href: '/cap-pacelc',
          description: 'P fixo, C vs A, L vs C.',
          customProps: {date: '13 set 2026'},
        },
        {
          type: 'link',
          label: 'Generics em Go',
          href: '/go-generics',
          description: 'Constraints, type sets e Cache pronto.',
          customProps: {date: '12 set 2026'},
        },
        {
          type: 'link',
          label: 'Erros e logs em Go',
          href: '/go-erros-logs',
          description: '%w, Is/As e slog estruturado.',
          customProps: {date: '12 set 2026'},
        },
        {
          type: 'link',
          label: 'Concorrência em Go',
          href: '/go-concorrencia',
          description: 'Goroutines, channels e race detector.',
          customProps: {date: '12 set 2026'},
        },
        {
          type: 'link',
          label: 'Maps em Go',
          href: '/go-maps',
          description: 'Swiss Tables: grupos, probing e crescimento.',
          customProps: {date: '12 set 2026'},
        },
        {
          type: 'link',
          label: 'Slices em Go',
          href: '/go-slices',
          description: 'Header, backing array, append e aliasing.',
          customProps: {date: '12 set 2026'},
        },
        {
          type: 'link',
          label: 'Interfaces em Go',
          href: '/go-interfaces',
          description: 'Comportamento sem herança: nil tipado e design por contrato.',
          customProps: {date: '12 set 2026'},
        },
        {
          type: 'link',
          label: 'Visibilidade e packages em Go',
          href: '/go-visibilidade-pacotes',
          description: 'Maiúscula exporta: pacotes, construtores e callbacks.',
          customProps: {date: '12 set 2026'},
        },
        {
          type: 'link',
          label: 'Structs e methods em Go',
          href: '/go-structs-methods',
          description: 'Semântica de valor, receivers, layout e composição.',
          customProps: {date: '12 set 2026'},
        },
        {
          type: 'link',
          label: 'Ponteiros em Go',
          href: '/go-ponteiros',
          description: 'Valores, endereços e memória: quando (não) usar ponteiros.',
          customProps: {date: '12 set 2026'},
        },
        {
          type: 'link',
          label: 'Error handling em Go',
          href: '/go-error-handling',
          description: 'Quando o if err != nil é decisão e quando vira ruído.',
          customProps: {date: '06 set 2026'},
        },
        {
          type: 'link',
          label: 'De Swift para Go',
          href: '/swift-para-go',
          description: 'Guia para quem domina Swift: o que migra, o que não existe e o que engana.',
          customProps: {date: '06 set 2026'},
        },
        {
          type: 'link',
          label: 'Style Guide Go',
          href: '/go/style-guide',
          description: 'Minhas decisões de estilo com a razão de cada uma.',
          customProps: {date: '06 set 2026'},
        },
        {
          type: 'link',
          label: 'Guia dos guias de estilo do Go',
          href: '/go-style-guides',
          description: 'Effective Go, Google e Uber: como navegar e decidir.',
          customProps: {date: '06 set 2026'},
        },
        {
          type: 'link',
          label: 'Go Backend Roadmap',
          href: '/go/roadmap',
          description: 'A sequência de estudo para chegar ao backend.',
          customProps: {date: '05 set 2026'},
        },
        {
          type: 'link',
          label: 'Go 1.27: novidades',
          href: '/go-1-27-novidades',
          description: 'Mudanças da versão que importam para backend.',
          customProps: {date: '05 set 2026'},
        },
        {
          type: 'link',
          label: 'Go by Example',
          href: '/go/hello-world',
          description: 'Exemplos curtos da linguagem e biblioteca padrão.',
          customProps: {date: '05 set 2026'},
        },
      ],
    },
  ],
};

export default sidebars;
