import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  goByExampleSidebar: [
    'index',
    'hello-world',
    'values',
    'variables',
    'constants',
    'for',
    'if-else',
    'switch',
    'arrays',
    'slices',
    'maps',
    'functions',
    'multiple-return-values',
    'variadic-functions',
    'closures',
    'recursion',
    'range-over-built-in-types',
    'pointers',
    'strings-and-runes',
    'structs',
    'methods',
    'interfaces',
    'enums',
    'struct-embedding',
    'generics',
    'range-over-iterators',
    'errors',
    'custom-errors',
    'goroutines',
    'channels',
    'channel-buffering',
    'channel-synchronization',
    'channel-directions',
    'select',
    'timeouts',
    'non-blocking-channel-operations',
    'closing-channels',
    'range-over-channels',
    'timers',
    'tickers',
    'worker-pools',
    'waitgroups',
    'rate-limiting',
    'atomic-counters',
    'mutexes',
    'stateful-goroutines',
    'sorting',
    'sorting-by-functions',
    'panic',
    'defer',
    'recover',
    'string-functions',
    'string-formatting',
    'text-templates',
    'regular-expressions',
    'json',
    'xml',
    'time',
    'epoch',
    'time-formatting-parsing',
    'random-numbers',
    'number-parsing',
    'url-parsing',
    'sha256-hashes',
    'base64-encoding',
    'reading-files',
    'writing-files',
    'line-filters',
    'file-paths',
    'directories',
    'temporary-files-and-directories',
    'embed-directive',
    'testing-and-benchmarking',
    'command-line-arguments',
    'command-line-flags',
    'command-line-subcommands',
    'environment-variables',
    'logging',
    'http-client',
    'http-server',
    'tcp-server',
    'context',
    'spawning-processes',
    'execing-processes',
    'signals',
    'exit',
  ],
  goEditorialSidebar: [
    {type: 'doc', id: 'index', label: 'Início'},
    {
      type: 'category',
      label: '2026',
      collapsible: false,
      items: ['roadmap'],
    },
  ],
};

export default sidebars;
